### ISSUE TITLE
The git-core package is not mandatory

### ISSUE THREAD

**Issue by kmelia** [bobthecow/git-flow-completion#39]
Hi,

On the [documentation for Ubuntu](https://github.com/bobthecow/git-flow-completion/wiki/Install-Bash-git-completion#ubuntudebian), you tell it to install the ``git-core`` package: but it is not mandatory to works out.

You can modify the documentation, like:
```sh
sudo apt-get install git bash-completion
```

I tried and all is working on my Ubuntu 14.04 LTS

Thanks in advance.

**Comment by bobthecow** [comment]
It's a wiki, feel free to update it ;)

Is it possible that this is a Debian requirement, or that it used to be a requirement, but has changed? If so, we should add a note that older versions of Ubuntu and/or Debian might need `git-core`

**Comment by kmelia** [comment]
> Is it possible that this is a Debian requirement, or that it used to be a requirement, but has changed?

Yes, It seems that is a transitional dummy package for ``git`` on [debian squeeze/wheezy/jessie/sid](https://packages.debian.org/en/squeeze/git-core) and on [ubuntu precise/trusty](http://packages.ubuntu.com/en/precise/git-core).

The ``git-core`` package only exists for Ubuntu Lucid (``git`` package does not exists), but the Ubuntu Lucid LTS version will be deprecated for server in one month and is already deprecated for desktop since 2 years ^^

So I think we could avoid adding a special note ?

**Comment by kmelia** [comment]
It is done on the wiki:
https://github.com/bobthecow/git-flow-completion/wiki/Install-Bash-git-completion/_compare/fcfb1fcd86ecb3ae174354860f4d64434947422f...edd175b327d3288ab275662d03973c3effc098d9

Thanks @bobthecow.
